-- Table ListUnit

-- Unité Infanterie
INSERT INTO ListUnit(UnitFR, UnitEN,InfuenceMax,LvlMax,Maitrise,TypeUnit,ForceUnit,Img) VALUES
('Hallebardiers','Halberdiers',165,18,1,'Infanterie','T3','./img/unit/hallebardiers.jpg'),
('Fils de Fenrir','Sons of Fenrir',175,18,0,'Infanterie','T3','./img/unit/filsFenrir.jpg'),
('Piquiers du Wuxing','Wuxing',155,18,0,'Infanterie','T3','./img/unit/piquiersWuxing.jpg'),
('Piquiers impériaux','Imperial Pikemen',240,24,1,'Infanterie','T4','./img/unit/piquiersImperiaux.jpg'),
('Fortebraccio','Fortebraccio',235,24,0,'Infanterie','T4','./img/unit/piquiersFortebraccio.jpg'),
('Prévôts hallebardiers','Provost Halberdiers',230,24,1,'Infanterie','T4','./img/unit/prevot_hallebardier.PNG'),
('Gardes du palais','Palace Guards',235,24,1,'Infanterie','T4','./img/unit/gardesPalais.jpg'),
('Azaps','Azaps',240,24,0,'Infanterie','T4','./img/unit/azaps.jpg'),
('Tseregs','Tseregs',235,24,0,'Infanterie','T4','./img/unit/tseregs.jpg'),
('Pillard fendeurs','Cleaver Raiders',240,24,0,'Infanterie','T4','./img/unit/pilardsFendeurs.jpg'),
('Housecarls','Housecarls',240,24,0,'Infanterie','T4','./img/unit/housecarls.jpg'),
('Claymores','Claymores',245,24,0,'Infanterie','T4','./img/unit/claymores.jpg'),
('Paladin symmachéen','Symmachean Paladin',245,24,0,'Infanterie','T4','./img/unit/paladinsSymmacheens.jpg'),
('Berserkers','Berserkers',245,24,0,'Infanterie','T4','./img/unit/berserkers.jpg'),
('Lanciers impériaux','Imperial Lancers',230,24,1,'Infanterie','T4','./img/unit/lanciers_imperiaux.PNG'),
('Fidèles symmachéen','Symmachean Faithful',240,24,0,'Infanterie','T4','./img/unit/fidelesSymmacheens.jpg'),
('Mirmillons','Myrmidons',245,24,0,'Infanterie','T4','./img/unit/mirmillons.PNG'),
('Vigile grisonnants','Grizzled Vigil',200,24,0,'Infanterie','T4','./img/unit/vigilesGrisonnants.jpg'),
('Javeliniers impériaux','Imperial Javelineers',240,24,1,'Infanterie','T4','./img/unit/javeliniersImperiaux.jpg'),
('Prévôts javeliniers','Provost Javelineers',230,24,1,'Infanterie','T4','./img/unit/prevotsJaveliniers.jpg'),
('Prévôts lanciers','',215,24,0,'Infanterie','T4','./img/unit/prevotsLanciers.jpg'),
('Moines au croissant','Crescent Monks',250,24,0,'Infanterie','T4','./img/unit/moinesCroissant.jpg'),
('Onna-bugeishas','Onna-bugeisha',235,24,0,'Infanterie','T4','./img/unit/onnaBugeishas.jpg'),
('Hommes d''armes','Men-at-Arms',215,24,0,'Infanterie','T4','./img/unit/hommesArmes.jpg'),
('Silahdars','Silahdars',320,30,0,'Infanterie','T5','./img/unit/silahdar.PNG'),
('Skjalmös','Skjalmös',310,30,0,'Infanterie','T5','./img/unit/valkyrie.PNG'),
('Fauchefers','Iron Reapers',315,30,0,'Infanterie','T5','./img/unit/fauchefer.PNG'),
('Gardes modao','Modao Guards',315,30,0,'Infanterie','T5','./img/unit/modao.PNG'),
('Samouraïs orochis','Orochi Samurai',295,30,0,'Infanterie','T5','./img/unit/samouraisOrochis.jpg'),
('Zweihanders','Zweihanders',310,30,0,'Infanterie','T5','./img/unit/Zweihanders.jpg'),
('Alchimistes','',60,18,0,'Infanterie','T3','./img/unit/alchimistes.jpg'),
('Condottières','',160,18,0,'Infanterie','T3','./img/unit/condottieres.jpg'),
('Cornemuseurs','',90,18,0,'Infanterie','T3','./img/unit/cornemuseurs.jpg'),
('Dimachères','Dimachaeri',165,18,0,'Infanterie','T3','./img/unit/dimacheres.jpg'),
('Écuyers','',155,18,0,'Infanterie','T3','./img/unit/ecuyers.jpg'),
('Gardes Préfectoraux','Prefectural Guards',170,18,1,'Infanterie','T3','./img/unit/gardesPrefectoraux.jpg'),
('Gardes varègues','Varangian Guard',290,30,0,'Infanterie','T5','./img/unit/gardesVaregues.jpg'),
('Gardes de Wuwei','Wuwei Guards',225,24,0,'Infanterie','T4','./img/unit/gardesWuwei.jpg'),
('Gonfanonniers','Gonfaloniers',225,24,0,'Infanterie','T4','./img/unit/gonfalonniers.jpg'),
('Hashashins','Hashashins',295,30,0,'Infanterie','T5','./img/unit/hashashins.jpg'),
('Jangjus','',170,30,0,'Infanterie','T3','./img/unit/jangjus.jpg'),
('Lanciers du dragon noir','',80,20,0,'Infanterie','T3','./img/unit/lanciersDragonNoir.jpg'),
('Lanciers têtes de fer','Ironhead Lancers',130,18,1,'Infanterie','T3','./img/unit/lanciersTeteDeFer.jpg'),
('Moines guerriers','',145,18,0,'Infanterie','T3','./img/unit/moinesGuerriers.jpg'),
('Naginata','',125,20,0,'Infanterie','T3','./img/unit/naginata.jpg'),
('Gardes royaux de Perceval','Perceval’s Royal Guards',225,24,0,'Infanterie','T4','./img/unit/percevalJav.jpg'),
('Piquiers du dragon noir','',80,20,0,'Infanterie','T3','./img/unit/piquiersDragonNoir.jpg'),
('Piquiers préfectoraux','Prefectural Pikemen',165,18,0,'Infanterie','T3','./img/unit/piquiersPrefectoraux.jpg'),
('Prévôts marteleurs','',150,18,1,'Infanterie','T3','./img/unit/prevotsMarteleurs.jpg'),
('Chevalier de la reine','Queen''s Knight',295,30,0,'Infanterie','T5','./img/unit/queenKnight.jpg'),
('Rétiaires','Retiarii',305,30,0,'Infanterie','T5','./img/unit/retiaires.jpg'),
('Ronins','',145,18,0,'Infanterie','T3','./img/unit/ronins.jpg');

-- Unité Distant
INSERT INTO ListUnit(UnitFR, UnitEN,InfuenceMax,LvlMax,Maitrise,TypeUnit,ForceUnit,Img) VALUES
('Milice zykalienne','Zykalian Militia',175,15,0,'Distant','T3','./img/unit/miliceZykalienne.jpg'),
('Pyro-Archers','Pyro-Archers',180,18,0,'Distant','T3','./img/unit/pyroArchers.jpg'),
('Jannisaires','Janissaries',190,19,0,'Distant','T3','./img/unit/janissaires.jpg'),
('Schutzdieners','Schutzdieners',155,18,0,'Distant','T3','./img/unit/schutzdieners.jpg'),
('Archers gallos','Gallian Archers',245,24,0,'Distant','T4','./img/unit/archer_gallos.PNG'),
('Archers impériaux','Imperial Archers',255,24,0,'Distant','T4','./img/unit/archersImperiaux.jpg'),
('Arquebusiers du Krieskrat','Krieskrat Arquebusiers',255,24,1,'Distant','T4','./img/unit/arquebusiersKriegsrat.jpg'),
('Arquebusiers impériaux','Imperial Arquebusiers',255,24,0,'Distant','T4','./img/unit/arquebusiersImperiaux.jpg'),
('Siphonaros','Siphonaros',330,30,0,'Distant','T5','./img/unit/siphonaros.jpg'),
('Falconetti','Falconetti',330,30,0,'Distant','T5','./img/unit/falconetti.PNG'),
('Veneurs','Huntsmen',320,30,0,'Distant','T5','./img/unit/veneurs.jpg'),
('Arbalétriers pavoiseurs','Pavise Crossbowmen',325,30,0,'Distant','T5','./img/unit/arbaletrier_pavoiseur.PNG'),
('Arquebusiers tercios','Tercio Arquebusiers',310,30,0,'Distant','T5','./img/unit/arquebusiersTercios.jpg'),
('Grenadier de Shenji','Shenji Grenadiers',315,30,0,'Distant','T5','./img/unit/grenadier_de_shenji.PNG'),
('Arbalétriers avant-garde','',160,18,0,'Distant','T3','./img/unit/arbaletriersAvantGarde.jpg'),
('Arbalétriers à plumes','Feathered Crossbowmen',150,18,0,'Distant','T3','./img/unit/arbaletriersPlumes.jpg'),
('Archers avant-garde','',150,18,0,'Distant','T3','./img/unit/archersAvantGarde.jpg'),
('Archers de namkhan','',180,18,0,'Distant','T3','./img/unit/archersNamkhan.jpg'),
('Archers préfectoraux','',180,18,0,'Distant','T3','./img/unit/archersPrefectoraux.jpg'),
('Archers vipères','',155,18,0,'Distant','T3','./img/unit/archersViperes.jpg'),
('Arquebusiers Ashigarus','',205,24,0,'Distant','T4','./img/unit/arquebusiersAshigarus.jpg'),
('Arquebusiers domaine','',170,18,0,'Distant','T4','./img/unit/arquebusiersDomaine.jpg'),
('Faucheurs Épieurs des Mers','',80,20,0,'Distant','T4','./img/unit/faucheursEpieursMers.jpg'),
('Javeliniers du dragon noir','',80,20,0,'Distant','T3','./img/unit/javeliniersDragonNoir.jpg'),
('Maîtres de la Chu-Ko-Nu','Chu-Ko-Nu',175,18,0,'Distant','T3','./img/unit/maitresChuKoNu.jpg');

-- Unité Cavalerie
INSERT INTO ListUnit(UnitFR, UnitEN,InfuenceMax,LvlMax,Maitrise,TypeUnit,ForceUnit,Img) VALUES
('Chevaucheurs','Riders',180,18,0,'Cavalerie','T3','./img/unit/chevaucheurs.jpg'),
('Pionniers du Selem','Selem Rider',150,18,0,'Cavalerie','T3','./img/unit/pionniersSelem.jpg'),
('Lancier avec esponton','Spearman with Spontoon',240,24,0,'Cavalerie','T4','./img/unit/lanciersEsponton.jpg'),
('Cavaliers lourds préfectoraux','Prefectural Heavy Cavalry',240,24,0,'Cavalerie','T4','./img/unit/cavaliersLourdsPrefectoraux.jpg'),
('Lanciers ribauds','Ribald Lancers',240,24,0,'Cavalerie','T4','./img/unit/lanciersRibauds.jpg'),
('Cavaliers kevthuuls','Kevthuul Riders',245,24,0,'Cavalerie','T4','./img/unit/cavaliersKevthuuls.jpg'),
('Cyphaux','',215,24,0,'Cavalerie','T4','./img/unit/cyphaux.jpg'),
('Chamelier lanciers','Camel Rider',225,24,0,'Cavalerie','T4','./img/unit/chameliersLanciers.jpg'),
('Kriegsbruders','Kriegsbruders',230,24,0,'Cavalerie','T4','./img/unit/kriegsbruders.jpg'),
('Cataphractaires lanciers','Cataphract Lancers',310,30,0,'Cavalerie','T5','./img/unit/cataphractairesLanciers.jpg'),
('Hussards ailés','Winged Hussars',315,30,0,'Cavalerie','T5','./img/unit/hussardsAiles.jpg'),
('Eclaireurs de Liao','Liao Scouts',315,30,0,'Cavalerie','T5','./img/unit/eclaireursLiao.jpg'),
('Kheshigs','Kheshigs',310,30,0,'Cavalerie','T5','./img/unit/kheshigs.PNG'),
('Templiers','Templars',305,30,0,'Cavalerie','T5','./img/unit/templiers.jpg'),
('Maître de la chu ko nu montés','Mounted Chu Ko Nu',305,30,0,'Cavalerie','T5','./img/unit/maitresChuKoNuMontes.jpg'),
('Bannerets','Bannerets',340,30,0,'Cavalerie','T5','./img/unit/bannerets.jpg'),
('Cavaliers de Yanyuedao','Yanyuedao Cavalry',320,30,0,'Cavalerie','T5','./img/unit/cavaliersYanyuedao.jpg'),
('Cavalier de Karadoc','Karadoc Rider',195,18,0,'Cavalerie','T3','./img/unit/caradocCav.jpg'),
('Cavaliers lourds de Xuanjia','Xuanjia Heavy Cavalry',305,30,0,'Cavalerie','T5','./img/unit/cavaliersLourdsXuanjia.jpg'),
('khorchins','',140,18,0,'Cavalerie','T3','./img/unit/khorchins.jpg'),
('Pyro-lanciers','',285,30,0,'Cavalerie','T5','./img/unit/pyroLanciers.jpg'),
('Yeomen','',225,24,0,'Cavalerie','T4','./img/unit/yeomen.jpg');


