CREATE TABLE IF NOT EXISTS Forum (
    ID INTEGER PRIMARY KEY,
    Author INTEGER NOT NULL,
    Date VARCHAR(100) NOT NULL,
    Title VARCHAR(250) NOT NULL,
    Content VARCHAR(5000) NOT NULL,
    Image VARCHAR(1000) DEFAULT "",
    Valid INTEGER DEFAULT 0,
    Archive INTEGER DEFAULT 0,
    FOREIGN KEY (Author) REFERENCES Users (ID),
);

CREATE TABLE IF NOT EXISTS Comments (
    ID INTEGER PRIMARY KEY,
    Post_ID INTEGER NOT NULL,
    Author INTEGER NOT NULL,
    Date VARCHAR(100) NOT NULL,
    Content VARCHAR(5000) NOT NULL,
    Image VARCHAR(1000) DEFAULT "",
    FOREIGN KEY (Post_ID) REFERENCES Forum (ID),
    FOREIGN KEY (Author) REFERENCES Users (ID),
);
