-- Table ListUnit

-- Unité Infanterie
INSERT INTO ListUnit(UnitFR, UnitEN,InfuenceMax,LvlMax,Maitrise,TypeUnit,ForceUnit,Img) VALUES
('Gardes varègues','Varangian Guard',290,30,0,1,'T5','./img/unit/gardes_varegues.jpg'),
('Silahdars','Silahdars',300,30,0,1,'T5','./img/unit/silahdars.png'),
('Skjaldmös','shieldmaidens',280,30,0,1,'T5','./img/unit/skjaldmos.png'),
('Fauchefers','Iron Reapers',300,30,0,1,'T5','./img/unit/fauchefer.png'),
('Gardes modao','Modao Guards',310,30,0,1,'T5','./img/unit/gardes_modao.png'),
('Rétiaires','Retiarii',305,30,0,1,'T5','./img/unit/retiaires.jpg'),
('Zweihanders','Zweihanders',310,30,0,1,'T5','./img/unit/zweihanders.jpg'),
('Hashashins','Hashashins',295,30,0,1,'T5','./img/unit/hashashins.jpg'),
('Chevalier de la reine','Queen''s Knight',295,30,0,1,'T5','./img/unit/chevalier_de_la_reine.jpg'),
('Phalange Solaire','Sunward phalanx',300,30,0,1,'T5','./img/unit/phalange_solaire.png'),
('Élus de Sparte',' Spartan Chosen',295,30,0,1,'T5','./img/unit/spartan_chosen.jpg'),
('Samouraïs orochis','Orochi Samurai',295,30,0,1,'T5','./img/unit/samourais_orochis.jpg'),
('Piquiers impériaux','Imperial Pikemen',240,24,1,1,'T4','./img/unit/piquiers_imperiaux.jpg'),
('Fortebraccio','Fortebraccio',235,24,0,1,'T4','./img/unit/fortebraccio.jpg'),
('Prévôts hallebardiers','Provost Halberdiers',230,24,1,1,'T4','./img/unit/prevots_hallebardiers.png'),
('Garde du palais','Palace Guards',230,24,1,1,'T4','./img/unit/gardes_palais.jpg'),
('Azaps','Azaps',225,24,1,1,'T4','./img/unit/azaps.jpg'),
('Tseregs','Tseregs',225,24,0,1,'T4','./img/unit/tseregs.jpg'),
('Pillard fendeur','Cleaver Raiders',240,24,0,1,'T4','./img/unit/pillard_fendeur.jpg'),
('Housecarls','Housecarls',240,24,0,1,'T4','./img/unit/housecarls.jpg'),
('Claymores','Claymores',245,24,0,1,'T4','./img/unit/claymores.jpg'),
('Gonfanonniers','Gonfaloniers',225,24,0,1,'T4','./img/unit/gonfalonniers.jpg'),
('Paladin symmachéen','Symmachean Paladin',235,24,1,1,'T4','./img/unit/paladin_symmacheen.jpg'),
('Berserkers','Berserkers',230,24,0,1,'T4','./img/unit/berserkers.jpg'),
('Lanciers impériaux','Imperial Lancers',240,24,1,1,'T4','./img/unit/lanciers_imperiaux.png'),
('Fidèles symmachéen','Symmachean Faithful',240,24,1,1,'T4','./img/unit/fideles_symmacheen.jpg'),
('Mirmillon','Myrmidons',245,24,0,1,'T4','./img/unit/mirmillon.png'),
('Vigile grisonant','Grizzled Vigil',200,24,0,1,'T4','./img/unit/vigile_grisonant.jpg'),
('Javeliniers impériaux','Imperial Javelineers',240,24,1,1,'T4','./img/unit/javeliniers_imperiaux.jpg'),
('Prévôts javeliniers','Provost Javelineers',230,24,1,1,'T4','./img/unit/prevots_javeliniers.jpg'),
('Moines au croissant','Crescent Monks',250,24,0,1,'T4','./img/unit/moines_au_croissant.jpg'),
('Onna-bugeishas','Onna-bugeisha',225,24,0,1,'T4','./img/unit/onna_bugeishas.jpg'),
('Hommes d''armes','Men-at-Arms',235,24,1,1,'T4','./img/unit/hommes_darmes.jpg'),
('Gardes royaux de Perceval','Perceval’s Royal Guards',225,24,0,1,'T4','./img/unit/gardes_royaux_de_perceval.jpg'),
('Gardes de Wuwei','Wuwei Guards',225,24,0,1,'T4','./img/unit/gardes_wuwei.jpg'),
('Javelots laconiques','Laconic Javelins',210,24,0,1,'T4','./img/unit/javelots_laconiques.jpg'),
('Prévôts lanciers','Spear sergeants',215,24,1,1,'T4','./img/unit/prevots_lanciers.jpg'),
('Hallebardiers','Halberdiers',165,18,1,1,'T3','./img/unit/hallebardiers.jpg'),
('Piquiers préfectoraux','Prefectural Pikemen',165,18,1,1,'T3','./img/unit/piquiers_prefectoraux.jpg'),
('Gardes Préfectoraux','Prefectural Guards',170,18,1,1,'T3','./img/unit/gardes_prefectoraux.jpg'),
('Lanciers têtes-de-fer','Ironhead Lancers',130,18,1,1,'T3','./img/unit/lanciers_tetes_de_fer.jpg'),
('Fils de Fenrir','Sons of Fenrir',165,18,0,1,'T3','./img/unit/fils_de_fenrir.jpg'),
('Dimachères','Dimachaeri',165,18,0,1,'T3','./img/unit/dimacheres.jpg'),
('Piquiers du Wuxing','Wuxing pikemen',155,18,0,1,'T3','./img/unit/piquiers_du_wuxing.jpg'),
('Auxiliaires hélotes','Helot Auxilary',70,18,0,1,'T3','./img/unit/auxiliaires_helotes.jpg'),
('Alchimistes','Alchemists',60,18,0,1,'T3','./img/unit/alchimistes.jpg'),
('Cornemuseurs','Bagpipers',75,18,0,1,'T3','./img/unit/cornemuseurs.jpg'),
('Moines guerriers','cudgel monks',145,18,0,1,'T3','./img/unit/moines_guerriers.jpg'),
('Lansquenets','Landsknechts',165,18,0,1,'T3','./img/unit/lansquenets.jpg'),
('Condottières','Condottieri guards',160,18,0,1,'T3','./img/unit/condottieres.jpg'),
('Lanciers du dragon noir','Black Dragon spearmen',80,20,0,1,'T3','./img/unit/lanciers_du_dragon_noir.jpg'),
('Javeliniers du dragon noir','Black Dragon Javelineers',80,20,0,1,'T3','./img/unit/javeliniers_du_dragon_noir.jpg'),
('Prévôts marteleurs','Mace sergeants',150,18,1,1,'T3','./img/unit/prevots_marteleurs.jpg'),
('Écuyers','Squires',155,18,1,1,'T3','./img/unit/ecuyers.jpg'),
('Jangjus','Jangjus',180,18,0,1,'T3','./img/unit/jangjus.jpg'),
('Naginata','Naginata monks',125,20,0,1,'T3','./img/unit/naginata.jpg'),
('Piquiers du dragon noir','Black Dragon Pikemen',80,20,0,1,'T3','./img/unit/piquiers_du_dragon_noir.jpg'),
('Ronins','Ronin',145,18,0,1,'T3','./img/unit/ronins.jpg');


-- Unité Distant
INSERT INTO ListUnit(UnitFR, UnitEN,InfuenceMax,LvlMax,Maitrise,TypeUnit,ForceUnit,Img) VALUES
('Siphonaros','Siphonaros',300,30,0,2,'T5','./img/unit/siphonaros.jpg'),
('Falconetti','Falconetti',300,30,0,2,'T5','./img/unit/falconetti.png'),
('Veneurs','Huntsmen',320,30,0,2,'T5','./img/unit/veneurs.jpg'),
('Arbalétriers pavoiseurs','Pavise Crossbowmen',325,30,0,2,'T5','./img/unit/arbaletriers_pavoiseurs.png'),
('Arquebusiers tercios','Tercio Arquebusiers',280,30,0,2,'T5','./img/unit/arquebusiers_tercios.jpg'),
('Grenadier de Shenji','Shenji Grenadiers',315,30,0,2,'T5','./img/unit/grenadier_de_shenji.png'),
('Équipe de Lionroar','Lionroar crew',320,30,0,2,'T5','./img/unit/equipe_de_lionroar.png'),
('Archers gallos','Gallian Archers',245,24,1,2,'T4','./img/unit/archer_gallos.png'),
('Archers impériaux','Imperial Archers',235,24,1,2,'T4','./img/unit/archers_imperiaux.jpg'),
('Arquebusiers du Kriegsrat','Kriegsrat Fusiliers',245,24,1,2,'T4','./img/unit/arquebusiers_du_kriegsrat.jpg'),
('Arquebusiers impériaux','Imperial Arquebusiers',255,24,1,2,'T4','./img/unit/arquebusiers_impériaux.jpg'),
('Plumes de porc','swinefeathers',235,24,0,2,'T3','./img/unit/plumes_de_porc.png'),
('Arquebusiers Ashigarus','Matchlock Ashigaru',205,24,0,2,'T4','./img/unit/arquebusiers_ashigarus.jpg'),
('Milice zykalienne','Zykalian Militia',175,18,0,2,'T3','./img/unit/milice_zykalienne.jpg'),
('Pyro-Archers','Pyro-Archers',180,18,0,2,'T3','./img/unit/pyro_archers.jpg'),
('Jannisaires','Janissaries',180,19,0,2,'T3','./img/unit/jannisaires.jpg'),
('Schutzdieners','Schutzdieners',155,18,0,2,'T3','./img/unit/schutzdieners.jpg'),
('Maîtres de la Chu Ko Nu','Ratan marksmen',175,18,1,2,'T3','./img/unit/maitres_de_la_chu_ko_nu.jpg'),
('Arbalétriers à plumes','Feathered Crossbowmen',150,18,0,2,'T3','./img/unit/arbalétriers_a_plumes.jpg'),
('Frondeurs Psiloi','Psiloi Slingers',90,18,0,2,'T3','./img/unit/frondeurs_psiloi.png'),
('Pistoleros Reitar','Reitar Pistoleers',190,18,0,2,'T3','./img/unit/pistoleros_reitar.png'),
('Archers de namkhan','Namkhan Archers',180,18,0,2,'T3','./img/unit/archers_de_namkhan.jpg'),
('Arbalétriers avant-garde','Demesne arbalists',160,18,0,2,'T3','./img/unit/arbaletriers_avant_garde.jpg'),
('Archers avant-garde','Vanguard Archers',150,18,0,2,'T3','./img/unit/archers_avant_garde.jpg'),
('Archers préfectoraux','Prefecture Archers',180,18,0,2,'T3','./img/unit/archers_prefectoraux.jpg'),
('Archers vipères','Rattan Vipers',155,18,0,2,'T3','./img/unit/archers_viperes.jpg'),
('Arquebusiers domaine','demesme Arquebusiers',170,18,0,2,'T4','./img/unit/arquebusiers_domaine.jpg'),
('Faucheurs des Épieurs des Mers','Sea stag deathdealers',175,20,0,2,'T4','./img/unit/faucheurs_des_epieurs_des_mers.jpg');

-- Unité Cavalerie
INSERT INTO ListUnit(UnitFR, UnitEN,InfuenceMax,LvlMax,Maitrise,TypeUnit,ForceUnit,Img) VALUES
('Cataphractaires lanciers','Cataphract Lancers',310,30,0,3,'T5','./img/unit/cataphractaires_lanciers.jpg'),
('Hussards ailés','Winged Hussars',305,30,0,3,'T5','./img/unit/hussards_ailes.jpg'),
('Eclaireurs de Liao','Liao Scouts',315,30,0,3,'T5','./img/unit/eclaireurs_de_liao.png'),
('Kheshigs','Kheshigs',300,30,0,3,'T5','./img/unit/kheshigs.png'),
('Templiers','Templars',295,30,0,3,'T5','./img/unit/templiers.jpg'),
('Maîtres de la Chu ko nu montés','Ratan ranger',295,30,0,3,'T5','./img/unit/maitres_de_la_chu_ko_nu_montes.jpg'),
('Bannerets','Bannerets',340,30,0,3,'T5','./img/unit/bannerets.jpg'),
('Cavaliers de Yanyuedao','Yanyuedao Cavalry',320,30,0,3,'T5','./img/unit/cavaliers_de_yanyuedao.jpg'),
('Cavaliers lourds de Xuanjia','Xuanjia Heavy Cavalry',305,30,0,3,'T5','./img/unit/cavaliers_lourds_de_xuanjia.jpg'),
('Pyro-lanciers','fire Lancers',285,30,0,3,'T5','./img/unit/pyro_lanciers.jpg'),
('Lancier avec Esponton','Spearman with Spontoon',240,24,0,3,'T4','./img/unit/lancier_avec_esponton.jpg'),
('Cavaliers lourds préfectoraux','Prefectural Heavy Cavalry',240,24,1,3,'T4','./img/unit/cavaliers_lourds_prefectoraux.jpg'),
('Lanciers ribauds','Ribald Lancers',235,24,0,3,'T4','./img/unit/lanciers_ribauds.jpg'),
('Cavaliers kevthuuls','Kevthuul Riders',245,24,0,3,'T4','./img/unit/cavaliers_kevthuuls.jpg'),
('Chamelier lanciers','Camel Lancers',225,24,0,3,'T4','./img/unit/chameliers_lanciers.jpg'),
('Kriegsbruders','Kriegsbruders',230,24,0,3,'T4','./img/unit/kriegsbruders.jpg'),
('Cavalerie des Compagnons','Companion Cavalry',230,24,0,3,'T4','./img/unit/cavalerie_des_compagnons.png'),
('Cyphaux','Sipahis',215,24,1,3,'T4','./img/unit/cyphaux.jpg'),
('Yeomen','Yeomen',225,24,1,3,'T4','./img/unit/yeomen.jpg'),
('Chevaucheurs','Riders',180,18,0,3,'T3','./img/unit/chevaucheurs.jpg'),
('Cavalier de Selem','Selem Rider',150,18,0,3,'T3','./img/unit/cavalier_de_selem.jpg'),
('Cavalier de Karadoc','Caradoc''s Cavalry',195,18,0,3,'T3','./img/unit/cavalier_de_karadoc.jpg'),
('khorchins','khorchins',140,18,0,3,'T3','./img/unit/khorchins.jpg');





