CREATE TABLE IF NOT EXISTS Forum (
    ID INTEGER PRIMARY KEY,
    Author INTEGER NOT NULL,
    Date VARCHAR(100) NOT NULL,
    Title VARCHAR(250) NOT NULL,
    Content TEXT NOT NULL,
    Valid INTEGER DEFAULT 0,
    Archive INTEGER DEFAULT 0,
    FOREIGN KEY (Author) REFERENCES Users (ID)
);

CREATE TABLE IF NOT EXISTS Comments (
    ID INTEGER PRIMARY KEY,
    Post_ID INTEGER NOT NULL,
    Author INTEGER NOT NULL,
    Date VARCHAR(100) NOT NULL,
    Content TEXT NOT NULL,
    FOREIGN KEY (Post_ID) REFERENCES Forum (ID),
    FOREIGN KEY (Author) REFERENCES Users (ID)
);
